name = "birdie"
version = "1.1.0"

description = "Snapshot testing in Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "giacomocavalieri", repo = "birdie" }
target = "erlang"

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
simplifile = "~> 1.2"
justin = "~> 1.0"
gleam_community_ansi = "~> 1.4"
argv = "~> 1.0"
gleam_erlang = "~> 0.24"
rank = "~> 1.0"
glance = "~> 0.8"
trie_again = "~> 1.1"
filepath = "~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.1"
